name: Build

on: 
  workflow_dispatch: 


jobs: 
  build: 
    name: Build and tests
    runs-on: macos-latest
    steps: 
      - uses: actions/checkout@v4
      - name: Setup Xcode version
        run: sudo xcode-select -switch /Aplications/Xcode_15.0.1.app
      - name: Show curret version of Xcode
        run: xcodebuild -version
      - name: Run tests
        run: ./run_tests.sh
