name: Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and tests
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: '15.0.1'
      - name: Show current version of Xcode
        run: xcodebuild -version
      - name: Run tests
        run: ./run_tests.sh