name: Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and tests
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Setup Xcode version
         run: xcrun simctl create 'iPhone 15' com.apple.CoreSimulator.SimDeviceType.iPhone-15 com.apple.CoreSimulator.SimRuntime.iOS-15-0 
      - name: Show current version of Xcode
        run: xcodebuild -version
      - name: Run tests
        run: ./run_tests.sh