# .github/workflows/lint.yml

name: SwiftLint

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened]

concurrency:
  # Cancel any in-progress workflows for this workflow/branch combination.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  SwiftLint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.1.app/Contents/Developer

      - name: Install SwiftLint
        run: |
          if ! swiftlint; then
            echo "SwiftLint not installed. Installing..."
            brew install swiftlint
          fi

      - name: Run SwiftLint on GitHub Actions
        run: swiftlint


