# .github/workflows/lint.yml

name: swiftlint

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
concurrency:
  # Cancel any in-progress workflows for this workflow/branch combination.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  swiftlint:
    runs-on: macos-13

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Xcode version
      run: sudo xcode-select -s /Applications/Xcode_15.1.app/Contents/Developer

    - name: Install SwiftLint
      run: |
        if ! swiftlint; then
          echo "SwiftLint not installed. Installing..."
          brew install swiftlint
        fi

    - name: Run SwiftLint
      run: swiftlint
