# .github/workflows/lint.yml

name: SwiftLint

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened]

permissions:
  contents: write
  pull-requests: write

concurrency:
  # Cancel any in-progress workflows for this workflow/branch combination.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  SwiftLint:
    runs-on: macos-13

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.1.app/Contents/Developer

      - name: Install SwiftLint
        run: |
          if ! swiftlint; then
            echo "SwiftLint not installed. Installing..."
            brew install swiftlint
          fi

      - name: Run SwiftLint locally
        run: swiftlint --fix

      - name: Commit changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "Auto-fix SwiftLint issues"

      - name: Push changes
        run: git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: Run SwiftLint on GitHub Actions
        run: swiftlint


