# .github/workflows/main.yml

name: main

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  # Cancel any in-progress workflows for this workflow/branch combination.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main:
    name: main
    runs-on: macos-13
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - uses: ./.github/workflows/lint.yml

    - uses: ./.github/workflows/build.yml
