name: Action_main

on:
  workflow_dispatch:
  workflow_run:
    workflows: [LintJob]
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [completed]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - name: Include SwiftLint Steps
        run: echo "::include ./.github/workflows/lint.yml"

      - name: Check Failure Status
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        run: |
          echo 'The triggered workflow failed.'
          exit 1

  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Include SwiftLint Steps
        run: echo "::include ./.github/workflows/build.yml"

      - name: Check Success Status
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        run: echo 'The triggered workflow was successful.'

      - name: Check Failure Status
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        run: |
          echo 'The triggered workflow failed.'
          exit 1

  Main:
    needs: [SwiftLint, Build]
    runs-on: ubuntu-latest
    steps:
      - name: Check Success Status
        if: ${{ needs.SwiftLint.outcome == 'success' && needs.Build.outcome == 'success' }}
        run: echo 'The triggered workflow was successful.'
      - name: Check Failure Status
        if: ${{ needs.SwiftLint.outcome == 'failure' || needs.Build.outcome == 'failure' }}
        run: |
          echo 'The triggered workflow failed.'
          exit 1
