# .github/workflows/main.yml

name: Action_main

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened ]
    
concurrency:
  # Cancel any in-progress workflows for this workflow/branch combination.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  LintJob:
    name: SwiftLint
    runs-on: macos-13

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Include SwiftLint Steps
        run: echo "::include ./.github/workflows/lint.yml"

  Build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Include SwiftLint Steps
        run: echo "::include ./.github/workflows/build.yml"


#  Main:
#    name: Action_main
#    runs-on: macos-13
#    needs: [lint, build]  # Dependencies on lint and build jobs
#
#    steps:
#    - name: Checkout code
#      uses: actions/checkout@v4
#
#    - name: Include SwiftLint Steps
#      run: echo "::include ./.github/workflows/lint.yml"
#
#    - name: Include Build Steps
#      run: echo "::include ./.github/workflows/build.yml"
