# .github/workflows/main.yml

name: Build and SwiftLint

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  # Cancel any in-progress workflows for this workflow/branch combination.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_swiftlint:
    name: Build and SwiftLint
    runs-on: macos-13

    steps:
    - uses: ./.github/workflows/lint.yml

    - uses: ./.github/workflows/build.yml